Fix for ESP32 with Compiler Warning:All
I got this error with ESP32 
error: suggest parentheses around comparison in operand of '&' [-Werror=parentheses]

When compiler warning is set on All, the code will not compile